appVersion: 2.14.0
description: CoreOS Dex
home: https://github.com/dexidp/dex/
icon: https://github.com/dexidp/dex/raw/master/Documentation/logos/dex-glyph-color.png
keywords:
- dex
- oidc
maintainers:
- email: Kevin.Fox@pnnl.gov
  name: kfox1111
- email: shane.starcher@gmail.com
  name: sstarcher
- email: pete.brown@powerhrg.com
  name: rendhalver
name: dex
version: 0.8.0
